name: aerosol-history
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - fair
  - h5py
  - iris
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scipy
  - statsmodels
  - tqdm
  - wquantiles
  - pip
  - pip:
    - climateforcing==0.1.0  # temp install with pip as this version not on conda
